### ISSUE TITLE
Issues deploying backend

### ISSUE THREAD

**Issue by jodi319** [jamesmontemagno/app-myshoppe#19]
I am having difficulty deploying the backend totally from VS to Azure.
When I try, it deploys with no errors - even says successful, but does not create the tables.
It does create the database, though.
What am I doing wrong?

Also, if wanted to add other tables, how exactly would I go about doing this?
I have never work with an actual SQL Server database via .Net implementation.
I have always only worked with Azure portal and Easy tables (Node.js).

Help please?

**Comment by jodi319** [comment]
I would love it if someone can respond to this. James?

**Comment by jamesmontemagno** [comment]
Take a look here for documentation: https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-backend-how-to-use-server-sdk

**Comment by jodi319** [comment]
I have worked with the mentioned  doc but still struggling.
I am trying to do everything from VS2015.
I added my own DTO's and successfully added my controller's via "New Scaffolding Item.." option - with success.
I leave the default Feedback and Store DTO's and controllers as is.
When I deploy; I specify new App, new resource group, new database server and new database - it deploys with no error - in fact the service launches in browser.
But when I try to view tables via VS2015 SQL Server Object Explorer, the dbserver and db exist with no tables. Not even Feedback or Store tables.
What am I doing wrong?

**Comment by jamesmontemagno** [comment]
Did you set a database connection?

![image](https://user-images.githubusercontent.com/1676321/28835675-0f438fbe-769b-11e7-826e-612a476679f6.png)

**Comment by jodi319** [comment]
I am doing everything via VS2015 (not portal), so yes, via the publish/deploy wizard I have created database connection.

**Comment by jodi319** [comment]
Is there if guide/ tutorial/doc around the the various ways of configuring SQL Server databases (not easy tables) within Azure and how to use it with Xamarin.Forms?
